random_adv/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  get '/sessions/new' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'

  post '/users/:user_id/prev_adventures/new' => 'prev_adventures#create'
  get '/uber' => 'uber#index'


  resources :users do 
    resources :adventures
    resources :prev_adventures
  end



end

random_adv/app/models/adventure.rb
class Adventure < ActiveRecord::Base
	has_many :prev_adventures
	has_many :users, through: :prev_adventures
end

random_adv/app/controllers/adventures_controller.rb
require "HTTParty"

class AdventuresController < ApplicationController

	def index
		#index not needed
	end

	def new
		@current_user = User.find(session[:user_id])

			#Wunderground weather API
			response = HTTParty.get("http://api.wunderground.com/api/abc3ed8ecb8d84a6/conditions/q/NY/new_york.json")
			temperature = response["current_observation"]["temp_f"]
			weather = response["current_observation"]["weather"]
			@icon = response["current_observation"]["icon_url"]
			@current_forecast = "#{weather} #{temperature} F°"

			@new_prev_adventure = PrevAdventure.new

		if logged_in? && check_current_user?
			@current_user = User.find(session[:user_id])
		else
			redirect_to user_path(actual_user)
		end
	end

	def show
	    @adv_id = params[:id]
	    @user_id = params[:user_id]
	    @current_adventure = PrevAdventure.where("adventure_id = ? AND user_id = ?", @adv_id, @user_id)
		
		#env variable key and HTTP response for Google API
		api_key = ENV["WING_IT_GOOGLE"]
		
		#for rendering page with their destination directions
		@adventure_choice = Adventure.find(params[:id])
		end_location = @adventure_choice.location
		@hint = @adventure_choice.hints
		@current_user = User.find(params[:user_id])

		#Google API variables to set the request
	    lat = cookies[:lat]
	    long = cookies[:long]
	    mode = @current_adventure.last.mode_of_travel
	    puts mode
	    #Google API request
		response = HTTParty.get("https://maps.googleapis.com/maps/api/directions/json?origin=#{lat},#{long}&destination=place_id:#{end_location}&mode=#{mode}&key=#{api_key}")
		puts response["routes"][0]["legs"][0]["travel_mode"]
		# @total_duration = response["routes"][0]["legs"][0]["duration"]
		@directions = response["routes"][0]["legs"][0]["steps"]

		client_id = "ucWa1PKE9x4YgQ_xouwuZFHRW1H-gGw9"
    	client_secret = "h_9nd2BUa1LVvLWJ9T2gkWDJ8BUW9ITUsEVvVlgR"
    	base_url = "https://login.uber.com/oauth/authorize"
    	query ={
        response_type: 'code',
        client_id: client_id,
        scope: 'request'
    	}
    	encoded_query = URI.encode_www_form(query)
    	@url = base_url + "?" + encoded_query

	end


	def create
		#gathering page information
		amount_time = params[:amount_time]
		amount_people = params[:amount_people]
		amount_spend = params[:amount_spend]
		mode_of_travel = params[:mode_of_travel]

		@user_id = params[:user_id]
		@current_user = User.find(session[:user_id])

		if logged_in? && check_current_user? #this is our definition of logged in
			@current_user = User.find(session[:user_id])
			redirect_to user_adventure_path(adventure)
		else
			redirect_to user_path(actual_user)
		end
	end
		


end

random_adv/app/views/adventures/index.html.erb
"hi"

random_adv/app/views/adventures/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<div class="row">
		<div class="col-md-3" id="left-bar">
			<h3>Welcome, <%= @current_user.name %>! </h3>
			<ul>
				<p><%= link_to "Past Adventures", user_prev_adventures_path(@current_user) %></p>
				<p><%= link_to "Edit Profile", edit_user_path(@current_user) %></p>
			</ul>
			<h3><img src="<%=@icon%>">&nbsp <%= @current_forecast %> </h3>
		</div>
		<div class="col-md-6">
			<h2>Enter info below to start on your adventure!</h2>


			<p>ENTER YOUR LOCATION, YOUR TIME FRAME, AND BUDGET TO START ON AN ADVENTURE!</p>


			<%= form_for @new_prev_adventure do |f| %>
			Enter your $
			<%= f.text_field_tag :amount_spend %> <br>
			Enter amount of people
			<%= f.text_field_tag :amount_people %> <br>
			Enter minutes for adventure
			<%= f.text_field_tag :amount_time %> <br>
			How would you like to get there?
			<%= f.select_tag :mode_of_travel, options_for_select (["Walk" => "Walking"], ["Bike" => "Bicycling"], ["Subway" => "Transit"], ["Drive" => "Driving"]) %>
			<%= f.submit_tag "submit" %>
			<% end %>


		</div>
		<div class="col-md-3" id="right-bar">
		</div>
	</div>
</body>
</html>

random_adv/app/views/adventures/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body class="body-background" background="http://www.markkowalk.com/wp-content/uploads/2012/02/Times-Square.jpg">

	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-6">
			<div class="big-directions">
				<div class="main-directions">
					<h1 class="hint" style="color:white"> <%= @hint %></h1>
					<div class="bar">
					</div>

					<% @directions.each do |turn| %>
					<div class="turn-directions">
						<li> <%= turn["html_instructions"].html_safe %>. &nbsp &nbsp<%= turn["distance"]["text"] %>, <%= turn["duration"]["text"] %></li>
						<!-- <p> <%= turn["distance"]["text"] %>, <%= turn["duration"]["text"] %> </p> -->
					</div>
					<% end %>
					<div>
						 <a href=<%=@url%>><button>UBER</button></a>
					</div>
	
			</div>
		</div>
	</div>

</body>
</html>